In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [8]:
### one hot Repre
one_hot_rep= [one_hot(words,voc_size)for words in sent]
one_hot_rep
# it is just giving the idea of that for examle word "of" is having 637 index "1" and rest other are zero

[[5963, 7493, 2467, 2066],
 [5963, 7493, 2467, 9054],
 [5963, 7654, 2467, 7104],
 [9953, 1831, 243, 149, 5896],
 [9953, 1831, 243, 149, 542],
 [3225, 5963, 1352, 2467, 2928],
 [5742, 4774, 5789, 149]]

In [11]:
##word embeding representation 
from pyexpat import model
from tensorflow.keras.layers import Embedding
#from tensorflow.kearas.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [13]:
import numpy as np

In [15]:
##we need to to make same size of all the sentences
#maxmium decided as seen from data sentences, 
sent_len =8 

#padding will add zeros in the places where sent size is less
#if we give pre zeros 0 will be added pre or post
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 5963, 7493, 2467, 2066],
       [   0,    0,    0,    0, 5963, 7493, 2467, 9054],
       [   0,    0,    0,    0, 5963, 7654, 2467, 7104],
       [   0,    0,    0, 9953, 1831,  243,  149, 5896],
       [   0,    0,    0, 9953, 1831,  243,  149,  542],
       [   0,    0,    0, 3225, 5963, 1352, 2467, 2928],
       [   0,    0,    0,    0, 5742, 4774, 5789,  149]])

In [16]:
##feature representation
##which means i want 10 dimension
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 66ms/step


array([[[ 0.03346327, -0.01861715,  0.03532964, -0.00238283,
         -0.0320212 , -0.01159451, -0.03817357,  0.02877488,
          0.00737559, -0.00827453],
        [ 0.03346327, -0.01861715,  0.03532964, -0.00238283,
         -0.0320212 , -0.01159451, -0.03817357,  0.02877488,
          0.00737559, -0.00827453],
        [ 0.03346327, -0.01861715,  0.03532964, -0.00238283,
         -0.0320212 , -0.01159451, -0.03817357,  0.02877488,
          0.00737559, -0.00827453],
        [ 0.03346327, -0.01861715,  0.03532964, -0.00238283,
         -0.0320212 , -0.01159451, -0.03817357,  0.02877488,
          0.00737559, -0.00827453],
        [ 0.01675398,  0.01086856, -0.01028901,  0.02238394,
          0.0345292 , -0.04178169, -0.03080568, -0.01603723,
         -0.01041921, -0.03259069],
        [-0.01212471, -0.01749869, -0.00363845, -0.00489416,
         -0.03718235, -0.04656733,  0.03610387, -0.00304042,
         -0.03158472, -0.021064  ],
        [-0.04775759, -0.02898875, -0.02658389,  0.0

In [20]:
embedded_docs[0]
#upper ka jo o/p data hai uska vector conversion and embeddings hai 

array([   0,    0,    0,    0, 5963, 7493, 2467, 2066])